@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 07 23:31:27 -0400 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim main_TB_behav -key {Behavioral:sim_1:Functional:main_TB} -tclbatch main_TB.tcl -view C:/Users/wangd/OneDrive/Desktop/CSE490 Proj1/main_TB_behav.wcfg -log simulate.log"
call xsim  main_TB_behav -key {Behavioral:sim_1:Functional:main_TB} -tclbatch main_TB.tcl -view C:/Users/wangd/OneDrive/Desktop/CSE490 Proj1/main_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
